version: '3.5'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -u app/app.py
    ports:
      - "5000:5000"
    networks:
      - hackernews_ops
      - elk
    volumes:
      - .:/app

networks:
  hackernews_ops:
    external: true
  elk:
    external: true

